version: "3"

services:
  # Postgres DB
  postgresdb:
    image: postgres
    container_name: postgres_db
    restart: unless-stopped
    tty: true
    ports:
      - "8832:5432"
    environment:
      POSTGRES_PASSWORD: 93QzUxBjUPsMhRk
      POSTGRES_USER: clonne
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - site-network

  # MySQL DB
  mysqldb:
    image: mysql:5.7.22
    container_name: mysql_db
    restart: unless-stopped
    tty: true
    ports:
      - "8833:3306"
    environment:
      MYSQL_USER: clonne
      MYSQL_PASSWORD: 93QzUxBjUPsMhRk
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - app-network

  # DB Manager
  adminer:
    image: adminer
    container_name: db_manager
    restart: unless-stopped
    tty: true
    ports:
      - "8022:8080"
    environment:
      ADMINER_DESIGN: lucas-sandery
      SERVICE_TAGS: dev
      SERVICE_NAME: adminer
    networks:
      - site-network

# Docker Networks
networks:
  site-network:
    driver: bridge

#Volumes
volumes:
  mysqldata:
    driver: local
  pgdata:
    driver: local
